# Generated by Django 4.1.6 on 2023-03-29 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_alttext_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='altText',
            field=models.TextField(default='Please describe some text that accurately represents the image!', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(upload_to='posts_pics'),
        ),
    ]
