# Generated by Django 4.2.6 on 2024-05-29 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='suggested_alt_text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='suggested_tags',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='post',
            name='alt_text',
            field=models.TextField(default='Write text that accurately describes the image!'),
        ),
    ]
